BM-927: Switch rpc for prover (#645)
Still getting 

```
error: Failed to get logs
5
2025-05-15T16:01:09.712-04:00
Caused by:
6
2025-05-15T16:01:09.712-04:00
0: Max retries exceeded HTTP error 503 with body: {"jsonrpc":"2.0","id":5398,"error":{"code":-32001,"message":"Unable to complete request at this time."}}
```

in the prover. Starting to think it may be a problem with the specific
rpc URL we are using, so switching to a different one (still Alchemy)